version: '2.2'
services:
        database:
                image: mysql
                ports:
                - "33060:3306"
                environment:
                - MYSQL_ROOT_PASSWORD=root
                - MYSQL_USER=admin
                - MYSQL_PASSWORD=pass
                - MYSQL_DATABASE=chitchat

